uutils/procps

.github/workflows/ci.yml

This PR removes the unmaintained `actions-rs/toolchain` and `actions-rs/cargo`. `actions-rs/toolchain` is replaced by `dtolnay/rust-toolchain` and `actions-rs/cargo` by direct invocations of `cargo`. It should fix many CI warnings.

ci: fix deprecation warnings by removing `actions-rs/cargo` and `actions-rs/toolchain`

---

src/uu/free/src/free.rs
tests/by-util/test_free.rs

The GNU free is using 11 chars wide for number, not 12. This was also causing a misalignment of the numbers with the title.
The source for the 11 chars wide: https://gitlab.com/procps-ng/procps/-/blob/master/src/free.c?ref_type=heads#L336

Fix output formatting for free

---

src/uu/w/src/w.rs
tests/by-util/test_w.rs

w: Implement --no-header

---

src/uu/free/src/free.rs

This PR should fix the "this import is redundant" clippy error on macOS.

free: remove redundant import on macOS

---

src/uu/free/src/free.rs
src/uu/w/src/w.rs

This PR fixes two issues that break the "Basic CI / cargo check (windows-latest)" check:
- an "unresolved import `uucore::utmpx`" error in `w`
- a "cannot find function `parse_meminfo` in this scope" error in `free`

ci: fix "Basic CI / cargo check (windows-latest)"

---

Cargo.toml

This PR adds `uudoc` as a feature to `Cargo.toml` to fix the warning "warning: invalid feature `uudoc` in required-features of target `uudoc`: `uudoc` is not present in [features] section".

Cargo.toml: add uudoc as feature

---

Cargo.toml
src/uu/w/Cargo.toml

This PR fixes two "unused manifest key" warnings from Cargo related to `utmpx` entries, see, for example, https://github.com/uutils/procps/actions/runs/8498779411/job/23278880657?pr=37#step:4:8.

Cargo.toml: remove utmpx

---

src/uu/free/src/free.rs

This PR should fix the "attempt to subtract with overflow" errors that make some tests fail on macOS. See, for example, https://github.com/uutils/procps/actions/runs/8505959792/job/23295337750?pr=37

free: prevent subtract with overflow on macOS

---

src/uu/watch/src/watch.rs
tests/by-util/test_watch.rs

This merge aims to add an interval parsing implementation for watch.
```
-n, --interval seconds
Specify update interval.  The command will not allow quicker than 0.1 second inter-
val,  in  which the smaller values are converted. Both '.' and ',' work for any lo-
cales. The WATCH_INTERVAL environment can be used to persistently set a non-default
interval (following the same rules and formatting).
```
In watch.rs, a new function named `parse_interval` is added, which takes in a `&str` and returns a result with `Duration` or an error with `ParseIntError`.
The function will first see if the string contains either a '.' or a ',' character. If it does not, it attempts to parse it into seconds and return a duration with that many seconds.
Otherwise, it will attempt to split the string into the …

watch: implement interval

---

Cargo.lock
Cargo.toml
src/uu/w/Cargo.toml
src/uu/w/src/w.rs
tests/by-util/test_w.rs

This change allows w to display time in a similar way to the original procps w. Additionally, w now fetches the cmdline for each entry.
Later, the fetch_cmdline and possibly format_time functions could be seperated out into a shared library for future applications, such as `ps` or `top`.

w: Format time and get cmdline

---

tests/by-util/test_watch.rs

This PR disables some tests on Windows as they fail because there is no `true` program on Windows.

watch: disable some tests on Windows

---

src/uu/w/src/w.rs

This PR should fix the clippy errors on Windows.

w: disable functions unused on Windows

---

Cargo.lock
src/uu/w/Cargo.toml
src/uu/w/src/w.rs
tests/by-util/test_w.rs

The w manpage defines JCPU as the total CPU time of all processes under a given tty. The PCPU is defined as being the total time being used by the command in the "what" field.
For the JCPU implementation, the program creates a hashmap of all terminal numbers and their total time by walking the pid folders in /proc. I don't think this is terrible performance-wise, as execution time is still slightly faster than the original w, when built in release mode.
Total time for a process is calculated by taking the sum of time scheduled in both user mode and kernel mode and dividing that by the system's clock tick.
In terms of tests, I've added a couple of unit tests and updated the test_output_format to make sure the JCPU and PCPU fields are populated, these still need to be formatted, so the …

w: Implement PCPU and JCPU

---

src/uu/slabtop/src/slabtop.rs

This PR separates header and slab list with an empty line to match the output of `procps-ng/slabtop`.

slabtop: separate header and slab list

---

src/uu/slabtop/src/parse.rs
tests/by-util/test_slabtop.rs

This PR moves the `slabtop` unit tests from `tests/by_util/test_slabtop.rs` to `src/uu/slabtop/src/parse.rs`. It fixes the "multiple associated items are never used" warnings shown by rust-analyzer in `parse.rs`.

slabtop: move unit tests to parse.rs

---

tests/by-util/test_w.rs

This PR fixes two clippy warnings in tests.

w: fix two clippy warnings in tests

---

.github/workflows/ci.yml

This PR adds `--all-targets` when running `clippy` to detect issues in tests, too.

ci: use --all-targets with clippy

---

tests/common/util.rs

This PR replaces `MAIN_SEPARATOR.to_string()` with `MAIN_SEPARATOR_STR`.

util.rs: use MAIN_SEPARATOR_STR

---

src/uu/w/src/w.rs
tests/by-util/test_w.rs

This PR adds `--help`. It also ensures that `-h` is the short form of `--no-header`.

w: add `--help`

---

src/uu/w/main.rs

Currently, there are two `main.rs` files: one in `src/uu/w` and the other in `src/uu/w/src`. The first looks like it's a left-over and so this PR deletes it.

w: delete unnecessary `main.rs`

---

src/uu/w/src/w.rs
tests/by-util/test_w.rs

We check for the parameter `-s | --short`. If it is set we exclude printing of `login time`, `JCPU time` and `PCPU time`.
Added a test to make sure only necessary values are printed.

`w`: implement --short option

---

src/uu/free/src/free.rs

This PR adapts the column widths when using `--line` to match those of the original `free`. And it renames "CacheUse" to "CachUse".
Before change:
```
SwapUse            0 CacheUse     3952136  MemUse       3893340 MemFree      1165596
```
After change:
```
SwapUse           0 CachUse     3967332  MemUse     3857276 MemFree     1201724
```

free: fix column widths for `--line`

---

src/uu/free/src/free.rs

This PR sets the value name for `-c`/`--count` and `-s`/`--seconds` to match the help text. It also merges some imports.

free: set value name for `-c` and `-s`

---

tests/common/util.rs

This PR disables the recently introduced `unexpected_cfgs` lint (see https://blog.rust-lang.org/2024/05/06/check-cfg.html) on `tests/common/util.rs` to suppress a lot of warnings because its code contains many coreutils features not available in this project (see, for example, https://github.com/uutils/procps/actions/runs/8969718428/job/24631718644?pr=70#step:5:193).

tests/util.rs: disable `unexpected_cfgs` lint

---

src/uu/free/src/free.rs

This PR removes an unnecessary import to fix a clippy warning from the [legacy_numeric_constants](https://rust-lang.github.io/rust-clippy/master/index.html#/legacy_numeric_constants) lint introduced with Rust 1.79.

free: remove unnecessary import

---

.github/workflows/ci.yml

With the introduction of the `Code Quality` workflow the `clippy` job in the `Basic CI` workflow is no longer needed and so this PR removes it.

ci: remove clippy job from `Basic CI` workflow

---

src/uu/free/src/free.rs

I noticed that we use for all but two args the `arg!` macro. This PR uses the `arg!` macro for the remaining two args.

free: use `arg!` macro for all args

---

src/uu/slabtop/src/slabtop.rs
tests/by-util/test_slabtop.rs

This PR adds `-o`/`--once`, though the functionality itself was already there. It's the same we currently use for when there is no argument specified.

slabtop: add `-o`/`--once`

---

src/uu/pidof/src/pidof.rs
tests/by-util/test_pidof.rs

fix #119 
This commit implemented two usage of `-o` which are already implemented in GNU's implementation, but not in ours.
```shell
❯ cargo run pidof zsh
116473 116472 116401 116391
❯ cargo run pidof -o116473,116472 zsh
116401 116391
❯ cargo run pidof -o116473 -o116472 zsh
116401 116391
```
And the GNU's implementation:
```shell
❯ pidof zsh
116473 116472 116401 116391
❯ pidof -o116473,116472 zsh
116401 116391
❯ pidof -o116473 -o116472 zsh
116401 116391
```

pidof: Implemented `-o`

---

src/uu/pidof/src/pidof.rs
tests/by-util/test_pidof.rs

fix #118
This commit fixed `-s` flag only output one result.
Before this commit:
```shell
❯ cargo run pidof -s zsh zsh zsh
218159
```
After:
```shell
❯ cargo run pidof -s zsh zsh zsh
218159 218159 218159
```
The behavior of uutils' implementation are as same as GNU's implementation now.
```shell
❯ cargo run pidof -s zsh zsh zsh
218159 218159 218159
❯ pidof -s zsh zsh zsh
218159 218159 218159
```

pidof: Return multiple PIDs while multiple program

---

src/uu/free/src/free.rs

fix #74
This commit fixed the issues about units in `free` command.
Before this commit, the `free` command use the wrong implementation
of the units conversion which caused by default flag `--kilo`.
The output of `--kilo` now as blow.
```shell
❯  cargo run free --kilo
total
Mem:        33033961
Swap:              0
❯ free --kilo
total
Mem:        33033961
Swap:              0
```

free: Fix free: `--kilo` returns the same as `--kibi` #74

---

src/uu/pgrep/src/pgrep.rs
tests/by-util/test_pgrep.rs

This PR allows the `--older` option without a pattern: `pgrep --older=1`. This corresponds to the behavior of `pgrep` from procps-ng.

pgrep: allow `--older` without pattern

---

src/uu/pgrep/src/pgrep.rs
tests/by-util/test_pgrep.rs

pgrep: allow `--terminal` without pattern

---

src/uu/pgrep/src/process.rs
tests/by-util/test_pgrep.rs

pgrep: Add `TerminalType::Unknown` and implement `Display` for `TerminalType`

---

src/uu/pgrep/src/pgrep.rs
tests/by-util/test_pgrep.rs

This PR allows a comma-separated list of terminals for `--terminal`.

pgrep: allow comma-separated list of terminals

---

src/uu/pgrep/src/pgrep.rs
tests/by-util/test_pgrep.rs

This PR allows the use of `--runstates` without a pattern. It also turns a regex pattern into a `const` in the tests.

pgrep: allow `--runstates` without pattern

---

tests/by-util/test_free.rs

This PR removes two redundant tests and applies some refactorings to the remaining tests:
* rename many vars
* use `lines()` instead of `split('\n')`
* test both short and long options
For reviewing, it's probably best to look at the commits in chronological order.

free: remove two tests & refactor remaining tests

---

.github/workflows/ci.yml

This PR removes `CARGO_FEATURES_OPTION` from the "Code Coverage" jobs because when it's used it is always empty.

ci: remove unused `CARGO_FEATURES_OPTION`

---

src/uu/pwdx/src/pwdx.rs
tests/by-util/test_pwdx.rs

This PR changes the error message that's shown when `pwdx 0` is called. Now it matches the error message shown by the original `pwdx`
```
// before
$ cargo run pwdx 0
pwdx: failed to read link for PID 0: No such file or directory (os error 2)
// after
$ cargo run pwdx 0
pwdx: invalid process id: 0
```

pwdx: handle `0` as invalid PID

---

Cargo.lock
src/uu/ps/Cargo.toml
src/uu/ps/src/parser.rs

Rust `1.80.1` shows some "dead code" warnings (see https://github.com/uutils/procps/actions/runs/10304214964/job/28522100251?pr=168#step:7:236):
```
error: variants `EmptyValue` and `ParsingFailed` are never constructed
--> src/uu/ps/src/parser.rs:12:5
|
10 | pub enum Error {
|          ----- variants in this enum
11 |     #[error("empty value")]
12 |     EmptyValue,
|     ^^^^^^^^^^
...
15 |     ParsingFailed,
|     ^^^^^^^^^^^^^
|
= note: `Error` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
= note: `-D dead-code` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(dead_code)]`
error: associated items `with_key`, `is_value_empty`, and `try_get` are never used
--> src/uu/ps/src/parser.rs:56:12
|
36 | impl …
```

ps: remove dead code

---

.github/workflows/ci.yml
Cargo.lock
src/uu/pwdx/Cargo.toml
src/uu/pwdx/src/pwdx.rs
tests/by-util/test_pwdx.rs

This PR uses the `sysinfo` crate to get the working directories of processes in a platform-independent way.

pwdx: use `sysinfo` crate

---

.github/workflows/code-quality.yml
src/uu/free/src/free.rs
src/uu/pgrep/src/pgrep.rs
src/uu/pidof/src/pidof.rs
src/uu/pidwait/src/pidwait.rs
src/uu/pidwait/src/wait.rs
src/uu/ps/src/collector.rs
src/uu/ps/src/sorting.rs
src/uu/slabtop/src/parse.rs
tests/by-util/test_free.rs
tests/by-util/test_w.rs

This PR runs the [semicolon_if_nothing_returned](https://rust-lang.github.io/rust-clippy/master/index.html#/semicolon_if_nothing_returned) lint in the CI and adds missing semicolons.

ci: run `semicolon_if_nothing_returned` lint

---

.github/workflows/code-quality.yml

I noticed that we run clippy up to three times if there is an error. I think this behavior is just copy/pasted from `coreutils` and probably not needed in this project. And so this PR makes clippy run only once.

ci: run clippy only once

---

src/uu/pmap/src/pmap.rs

A trivial refactoring: this PR moves the `uumain` function from the bottom of the file to (almost) the top of the file for better readability.

pmap: move `uumain` to top of file

---

src/uu/pmap/src/pmap.rs
tests/by-util/test_pmap.rs

This PR adds a new column to the output that shows the memory size when running `cargo run pmap <some PID>`. 
Before the change:
```
00007740f1b9a000 rw-p 00036000 08:08 10773308                   /usr/lib/ld-linux-x86-64.so.2
```
After the change:
```
00007740f1b9a000      8K rw-p 00036000 08:08 10773308                   /usr/lib/ld-linux-x86-64.so.2
```
In comparison, the output of the original `pmap`:
```
00007740f1b9a000      8K rw--- ld-linux-x86-64.so.2
```

pmap: add size column

---

src/uu/pmap/src/pmap.rs
tests/by-util/test_pmap.rs

This PR fixes the "perms" column and removes unnecessary columns from the output when running `cargo run pmap <some PID>`.
Before the changes:
```
0000735e54227000      8K rw-p 00036000 08:08 10773308                   /usr/lib/ld-linux-x86-64.so.2
```
After the changes:
```
0000735e54227000      8K rw--- /usr/lib/ld-linux-x86-64.so.2
```
In comparison, the output of the original `pmap`:
```
0000735e54227000      8K rw--- ld-linux-x86-64.so.2
```

pmap: fix perms column & remove unnecessary columns

---

src/uu/pmap/src/pmap.rs
tests/by-util/test_pmap.rs

This PR fixes the output of the "filename" column when running `cargo run pmap <PID>`. The output of the memory map should now match the output of the original `pmap`.
Before the changes:
```
000075ce972a3000      8K rw--- /usr/lib/ld-linux-x86-64.so.2
00007ffe29309000    132K rw--- [stack]
ffffffffff600000      4K --x-- [vsyscall]
```
After the changes:
```
000075ce972a3000      8K rw--- ld-linux-x86-64.so.2
00007ffe29309000    132K rw---   [ stack ]
ffffffffff600000      4K --x--   [ anon ]
```

pmap: fix "filename" column

---

src/uu/pmap/src/pmap.rs
tests/by-util/test_pmap.rs

This PR trims the return value of the `parse_cmdline` function.
Before the change, there is a space at the end of the output:
```
$ cargo run -q pmap 1 | tr " " "."
1:.../sbin/init.\vmlinuz-linux.
```
After the change:
```
$ cargo run -q pmap 1 | tr " " "."
1:.../sbin/init.\vmlinuz-linux
```

pmap: trim cmdline

---

src/uu/pidof/src/pidof.rs
tests/by-util/test_pidof.rs

I thought a bit about `pidof` and I think our implementation should match the `pidof` from `procps-ng`, and not the one from `sysvinit` that comes with Debian (there is a pending [proposal](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=810018) to switch to the `pidof` from `procps-ng`).
And so this PR adapts the options to those of the `pidof` from `procps-ng`. The functionality of the options seems to be the same, so no changes there. 
Before the changes:
```
Options:
-d <sep>          Use the provided character as output separator
-o <omitpid>      Omit results with a given PID
-q                Quiet mode. Do not display output
-s                Only return one PID
-h, --help        Print help
-V, --version     Print version
```
After the changes:
```
Options:
-S, --separator <SEP> …
```

pidof: adapt options to those of `pidof` from `procps-ng`

---

src/uu/watch/src/watch.rs

This PR fixes a warning from the [manual_pattern_char_comparison](https://rust-lang.github.io/rust-clippy/master/index.html#/manual_pattern_char_comparison) lint introduced with Rust 1.81.

watch: use array instead of closure

---

src/uu/free/src/free.rs
tests/by-util/test_free.rs

This PR adds a test for `-L`/`--line` and integrates an existing test into it. It also sets `args_override_self(true)`.

free: add test for `--line`

---

tests/by-util/test_pmap.rs

This PR fixes `test_multiple_existing_pids` that occasionally fails because it splits a vec at the wrong position.

pmap: improve where to split a vec in a test

---

src/uu/free/src/free.rs
tests/by-util/test_free.rs

This PR does three things:
- refactors `test_count` to get rid of `-s 0`, and `test_no_args` to extract code used by both test functions
- fails if `0` is provided for `-c`/`--count`
- fails if `0` is provided for `-s`/`--seconds`
The error messages are different from the original `free`, hopefully better.

free: fail if zero is provided for `-c`/`--count` or `-s`/`--seconds`

---

src/uu/pgrep/src/process.rs

pgrep: use rfind in stat split

---

tests/by-util/test_free.rs

This PR uses `assert_eq!` instead of `assert!` to ensure the equality of two values.

free: use `assert_eq!` instead of `assert!` in test

---

src/uu/pwdx/src/pwdx.rs

This PR uses `usize` instead of `i32` when parsing a PID and removes an unnecessary cast.

pwdx: use `usize` when parsing pid, not `i32`

---

README.md

I noticed that procps-ng contains two utilities we don't mention in our readme: `hugetop` (a new utility that will come with the next release) and `sysctl`. And so this PR adds them to our todo list.

readme: add `hugetop` & `sysctl` to todo list

---

src/uu/free/src/free.rs
tests/by-util/test_free.rs

When using something like `free --line -s1` or `free --line -c2`, the original `free` doesn't output an empty line between the entries whereas our implementation does. This PR removes this empty line from our output. It also does some refactorings to get rid of the variables `count_flag` and `seconds_flag` which are misleading as they don't represent boolean values.

free: use no empty line as delimiter with `--line`

---

build.rs

This PR removes some coreutils-related stuff from `build.rs`. And it fixes warnings from the (pedantic) [items_after_statements](https://rust-lang.github.io/rust-clippy/master/index.html#/items_after_statements) lint.

build.rs: remove coreutils stuff

---

src/uu/pmap/src/maps_format_parser.rs
src/uu/pmap/src/pmap.rs

This PR moves the parsing of the lines of `/proc/<PID>/maps` to its own file: `maps_format_parser.rs`. It also changes the return type of `parse_map_line()` from `(String, u64)` to `MapLine`, a new struct.
These changes were made in preparation for the implementation of `--device`, but I think they are useful on its own.

pmap: move parsing to `maps_format_parser.rs`

---

src/uu/pmap/src/pmap.rs

This PR uses constants for the options and sets `action(ArgAction::SetTrue)` for those that are flags.

pmap: use constants for options

---

src/uu/free/src/free.rs

This PR fixes the two "mismatched types" errors mentioned in #241

free: use references in test

---

src/uu/watch/src/watch.rs
tests/by-util/test_watch.rs

This commit adds Windows support to `watch`. To run commands, cmd.exe /C is used. In tests, rundll32.exe is used instead of true.

watch: Windows support

---

Cargo.lock
Cargo.toml
src/uu/free/Cargo.toml
src/uu/free/src/free.rs
src/uu/free/src/windows_util.rs

Values are virtual the same as resmon. Unfortunately, it is slightly hacky to get the page "Swap" file sizes.
I'm not sure about the name/location of the `windows_util.rs` file, let me know if you have a better name for that.
NOTE: I've noticed that the main coreutils crate uses `windows-sys` instead of `windows`. If this is something that needs to be done here, let me know.

free: add Windows support

---

src/uu/pmap/src/maps_format_parser.rs
src/uu/pmap/src/pmap.rs

This PR removes all `expect()`s from the parser, based on the feedback on https://github.com/uutils/procps/pull/249 . I put the changes in its own PR to keep #249 focused on the "device" format.

pmap: remove `expect()`s from parser & return `Result`

---

.github/workflows/ci.yml

I noticed that not all tests are run in the CI. This PR adds `--all` when running `cargo test`.
Currently, it should fail with two "mismatched types" errors, which I fixed in #242

ci: use `--all` when running `cargo test`

---

src/uu/pmap/src/maps_format_parser.rs
src/uu/pmap/src/pmap.rs
tests/by-util/test_pmap.rs

This PR implements `-d`/`--device` and creates output in the following format:
```
13176:   ../hello_world/target/debug/hello_world
Address           Kbytes Mode  Offset           Device    Mapping
000060ab2984a000      24 r---- 0000000000000000 008:00008 hello_world
000060ab29850000     248 r-x-- 0000000000006000 008:00008 hello_world
...
ffffffffff600000       4 --x-- 0000000000000000 000:00000   [ anon ]
mapped: 3060K    writeable/private: 348K    shared: 0K
```

pmap: implement `--device`

---

src/uu/pgrep/src/process.rs
src/uu/w/src/w.rs

This PR fixes the "unresolved imports" errors on macOS (see https://github.com/uutils/procps/actions/runs/11645635703/job/32438719489?pr=261#step:4:244) by making the `w` test module linux-only. It also makes two `pgrep` tests linux-only because they access `/proc` which is not available on macOS.

pgrep, w: make tests linux-only

---

Cargo.lock
Cargo.toml

This PR manually bumps `thiserror` from `1.0.63` to <del>`2.0.3`</del>`2.0.4` because `renovate` fails with an "Artifact update problem" (https://github.com/uutils/procps/pull/265).

Bump `thiserror` from `1.0.63` to `2.0.4`

---

tests/by-util/test_pgrep.rs
tests/by-util/test_pidof.rs

This PR fixes warnings from the [regex_creation_in_loops](https://rust-lang.github.io/rust-clippy/master/index.html#regex_creation_in_loops) lint introduced with Rust `1.84.0`.

tests: compile regexes outside of loop

---

tests/by-util/test_pgrep.rs

test_delimiter and test_delimiter_last_wins seem to rely on the system running the test having 2 or more 'sh' processes running, but that doesn't seem to be reliably the case in GitHub pipelines. Explicitly spawn two sleep processes instead.

test_pgrep: Try to fix flaky tests

---

Cargo.lock
Cargo.toml
tests/common/random.rs

This PR bumps `rand` from `0.8.5` to `0.9.0` and adapts `tests/common/random.rs` to the API changes.

Bump `rand` & adapt tests to its API changes

---

src/uu/pgrep/src/pgrep.rs
src/uu/pkill/src/pkill.rs
tests/by-util/test_pgrep.rs
tests/by-util/test_pkill.rs

Currently pgrep and pkill implement slightly different set command line args for process matching, even though both commands should support the same features. This PR extends the functionality of both tools to their superset of features. This will allow deduplicating the process matching part into a common module in a future PR.

Unify matching logic in pgrep and pkill

---

src/uu/pgrep/src/process.rs
src/uu/pidof/src/pidof.rs
tests/by-util/test_pidof.rs

This flag makes pidof print thread ids of threads belonging to the matching processes.

pidof: Support '-t' flag

---

src/uu/pgrep/src/pgrep.rs
src/uu/pgrep/src/process_matcher.rs
src/uu/pidwait/src/pidwait.rs
src/uu/pkill/src/pkill.rs
tests/by-util/test_pgrep.rs
tests/by-util/test_pkill.rs

Copy remaining process-matching feature of pidwait to process_matcher so pgrep and pkill can utilize it, then move pidwait to use the common process_matcher as well.

pidwait: Use common process_matcher (+ move a pidwait feature there)

---

src/uu/pgrep/src/process_matcher.rs
tests/by-util/test_pgrep.rs

The original `pgrep` shows a message if the pattern is longer than 15 chars:
```
$ pgrep 123456789012345
$ pgrep 1234567890123456
pgrep: pattern that searches for process name longer than 15 characters will result in zero matches
Try `pgrep -f' option to match against the complete command line.
```
We showed this message if the pattern was 15 chars or longer. This PR fixes the issue.

pgrep: don't show msg if pattern is 15 chars long

---

Cargo.lock
Cargo.toml
src/uu/free/src/free.rs

This PR bumps `bytesize` from `1.3` to `2.0` and adapts `free` to an API change (the function `to_string_as` got removed).

Bump `bytesize` and adapt `free` to API change

---

src/uu/pgrep/src/process_matcher.rs
tests/by-util/test_pgrep.rs

For example, pgrep should never report itself as a match (but it can match other pgrep processes).

process_matcher: Don't match own procps process

---

src/uu/pgrep/src/pgrep.rs
src/uu/pgrep/src/process.rs
src/uu/pgrep/src/process_matcher.rs
tests/by-util/test_pgrep.rs

Unlike pidof's similar option, the pgrep version will run the match predicates against every thread of the system and printing matching tids (unlike pidof which will run match predicates on every process of the system and then list every thread of every matched process).

pgrep: Support -w option

---

src/uu/pgrep/src/process.rs

While reviewing https://github.com/uutils/procps/pull/332 I noticed that our `pgrep` sometimes showed less PIDs than the original `pgrep`. The reason is we don't recognize some states like `I` as a valid state.
This PR adds the missing states `t` (trace stopped), `X` (dead), and `I` (idle) based on information in https://www.man7.org/linux/man-pages//man5/proc_pid_stat.5.html. I omitted the states only available with old kernel versions.

pgrep: add runstates `TraceStopped`, `Dead`, and `Idle`

---

.github/workflows/ci.yml
.github/workflows/code-quality.yml
Cargo.lock
Cargo.toml
src/uu/top/Cargo.toml
src/uu/top/build.rs
src/uu/top/src/header.rs
src/uu/top/src/picker.rs
src/uu/top/src/top.rs

Resolves #207 
Tasks:
I add crate `systemstat` for some of the values.
```text
top - 13:03:00 up 1:33, 1 user, load average: 2.01, 1.48, 1.28
Tasks: 1040 total, 6 running, 974 sleeping, 0 stopped, 0 zombie
%Cpu(s):  13.9 us, 3.3 sy, 0.0 ni, 82.4 id, 0.3 wa, 0.0 hi, 0.1 si, 0.0 st
MiB Mem :   7636.4 total,    433.3 free,   6415.1 used,    788.0 buff/cache
MiB Swap:  30518.0 total,  27218.5 free,   3299.5 used,   1221.3 avail Mem
```

top: implement SUMMARY display

---

tests/by-util/test_pidof.rs

This PR disables `test_find_init` as it recently started to fail in the CI (see https://github.com/uutils/procps/pull/355, https://github.com/uutils/procps/pull/356 and https://github.com/uutils/procps/pull/357) whereas it works locally.

pidof: disable "test_find_init", as it fails in CI

---

src/uu/pidof/src/pidof.rs
tests/by-util/test_pidof.rs

Currently, we require at least one program name and if none is provided, a clap error message is shown. This makes the following code snippet in `uumain` unreachable:
```rust
if arg_program_name.is_none() {
uucore::error::set_exit_code(1);
return Ok(());
};
```
This PR no longer requires a program name and thus makes the snippet above reachable. It also corresponds with the behavior of the original `pidof`, which doesn't show an error message if called without any args.
The PR also removes the `#[cfg(target_os = "linux")]` of the test as it is not necessary.

pidof: don't require program name

---

src/uu/pidof/src/pidof.rs
tests/by-util/test_pidof.rs

Lots of tests rely on finding kthreadd thus -w flag needs to be added to them.

pidof: Implement --with-workers

---

src/uu/sysctl/src/sysctl.rs

This PR renames a variable `splitted` to `split` because there is afaik no "splitted" in English.

sysctl: rename `splitted` to `split`

---

src/uu/pidof/pidof.md

This PR simplifies the usage string shown when using `--help`, using the same string as the original `pidof`.

pidof: simplify usage string

---

src/uu/w/src/w.rs

This is a basic implementation of the display of each users' idle time, as well as a dedicated time formatting function `format_time_elapsed` for this feature, as my first PR to the `uutils` project.
~~The code's logic is largely based on the original source of procps~~ We'll, no, as that is considered license violation. I mean just the logic is similar, but the code is rather another implementation.

w: implement idle_time and elapsed time formatting

---

src/uu/w/src/w.rs

This PR adapts the column widths of the `TTY` and `PCPU` columns to match those of the original `w`.
Before the change:
```
$ cargo run -q w
USER     TTY      LOGIN@   IDLE   JCPU   PCPU WHAT
...
```
After the change:
```
$ cargo run -q w
USER     TTY       LOGIN@   IDLE   JCPU   PCPU  WHAT
...
```
Original `w` (I omit the first line as we don't have implemented it yet in our version):
```
$ w
USER     TTY       LOGIN@   IDLE   JCPU   PCPU  WHAT
...
```

w: fix column widths

---

src/uu/pmap/src/pmap.rs
tests/by-util/test_pmap.rs

Resolves #376 
As the issue is not limited to `smaps`, several parts of the code are modified.

pmap: fixed to hide the header when permission is denied

---

Cargo.lock
Cargo.toml
README.md
src/uu/top/Cargo.toml
src/uu/top/src/header.rs
src/uu/vmstat/Cargo.toml
src/uu/vmstat/src/main.rs
src/uu/vmstat/src/parser.rs
src/uu/vmstat/src/vmstat.rs
src/uu/vmstat/vmstat.md
tests/by-util/test_vmstat.rs
tests/tests.rs

Add basic implementation of `vmstat` on Linux platform.
resolves #33

vmstat: add basic implementation of `vmstat`

---

src/uu/vmstat/src/vmstat.rs

fix #379 
now putput is like:
```text
$ cargo run -q vmstat
procs -----------memory---------- ---swap-- -----io---- -system-- -------cpu-------
r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st gu
1  0      0 6833000 335140 3992124  0    0  6168  1252 2863 8799  6  1 93  0  0  0
```

vmstat: fix format

---

src/uu/pgrep/src/process.rs
src/uu/snice/src/snice.rs
src/uu/top/src/picker.rs
src/uu/top/src/top.rs
tests/common/util.rs

This PR fixes warnings from the [double_ended_iterator_last](https://rust-lang.github.io/rust-clippy/master/index.html#double_ended_iterator_last), [manual_repeat_n](https://rust-lang.github.io/rust-clippy/master/index.html#manual_repeat_n), and [doc_overindented_list_items](https://rust-lang.github.io/rust-clippy/master/index.html#doc_overindented_list_items) lints.

clippy: fix warnings from Rust 1.86

---

src/uu/watch/src/watch.rs
tests/by-util/test_watch.rs

Resolves #25.
Handle `WATCH_INTERVAL`, as override for the `-n, --interval` option in `watch`.

watch: handle WATCH_INTERVAL

---

.github/workflows/ci.yml
.github/workflows/code-quality.yml

I noticed that we use two `fmt` jobs in the CI, one in each workflow. This PR moves the `fmt` job from the `ci` workflow to the `code-quality` workflow and removes the one existing there as it is much more complex.

ci: use only one of the fmt jobs & remove other

---

Cargo.lock
Cargo.toml

This PR manually bumps `crossterm` from `0.28.1` to `0.29.0` because renovatebot fails with a "Artifact update problem" (#390).

Bump `crossterm` from `0.28.1` to `0.29.0`

---

src/uu/w/Cargo.toml
src/uu/w/src/w.rs
tests/by-util/test_w.rs

fix #60 
output like:
```text
$ cargo run -q w
00:23:47  0:25,  0 user,  load average: 0.65, 0.50, 0.46
USER     TTY       LOGIN@   IDLE   JCPU   PCPU  WHAT
```

w: add uptime header

---

Cargo.lock
Cargo.toml
src/uu/vmstat/Cargo.toml
src/uu/vmstat/src/parser.rs
src/uu/vmstat/src/picker.rs
src/uu/vmstat/src/vmstat.rs
tests/by-util/test_vmstat.rs

vmstat: implement most functions

---

Cargo.lock
src/uu/top/Cargo.toml
src/uu/top/src/header.rs
src/uu/w/src/w.rs

procps uptime format from procps differs from coreutils'. 
for example:
coreutils:
```text
up 00:42
```
procps v4.0.5:
```text
up 42 min
```
also see [coreutils/7757](https://github.com/uutils/coreutils/pull/7757)

top, w: fix uptime format

---

Cargo.lock
Cargo.toml

This PR manually bumps `nix` from `0.29.0` to <del>`0.30.0`</del>`0.30.1` because renovate shows an "Artifact update problem" error in https://github.com/uutils/procps/pull/406

Bump `nix` from `0.29.0` to `0.30.1`

---

src/uu/pmap/src/maps_format_parser.rs
src/uu/pmap/src/pmap.rs
src/uu/pmap/src/pmap_config.rs
src/uu/pmap/src/smaps_format_parser.rs
tests/by-util/test_pmap.rs

Added support for the more-extended and most-extended options.

pmap: implemented more-extended and most-extended options

---

.github/workflows/ci.yml
src/uu/pmap/src/maps_format_parser.rs
src/uu/pmap/src/pmap.rs
src/uu/pmap/src/pmap_config.rs
tests/by-util/test_pmap.rs

Added support for the show-path option.

pmap: implemented show-path option

---

.github/workflows/ci.yml

In the CI we specify the version of `crossbeam-epoch` as a workaround for some issue. This PR removes this workaround in order to see whether it is still needed.

ci: remove hardcoded version of `crossbeam-epoch`

---

src/uu/pmap/src/pmap.rs
src/uu/pmap/src/pmap_config.rs
tests/by-util/test_pmap.rs

Added support for the quiet option.

pmap: implemented quiet option

---

src/uu/free/src/free.rs

- fix #73
```text
$ cargo run -q free -h && free -h && free
total        used        free      shared  buff/cache   available
Mem:            29Gi        13Gi       2.2Gi       2.4Gi        15Gi        15Gi
Swap:           22Gi          0B        22Gi
total        used        free      shared  buff/cache   available
Mem:            29Gi        13Gi       2.2Gi       2.4Gi        15Gi        15Gi
Swap:           22Gi          0B        22Gi
total        used        free      shared  buff/cache   available
Mem:        30517772    14584340     2340712     2487436    16534996    15933432
Swap:       23437308           0    23437308
```
tips: this is what procps actually doing, weird
```text
10138 * 1024 B -> "9.9Mi"
10230 * 1024 B -> "9Mi"
```
plus, humanization of procps differs from …

free: fix humanization

---

src/uu/pgrep/src/process.rs
src/uu/pgrep/src/process_matcher.rs
src/uu/pidwait/src/pidwait.rs
src/uu/ps/src/picker.rs

+ few misc cleanups to avoid leaking /proc internals

ps: support signal mask related fields

---

src/uu/w/src/w.rs

my username is `bluemangoo`
```
cargo run -q w
16:57:30 up  7:06,  4 users,  load average: 1.48, 1.07, 0.96
USER     TTY       LOGIN@   IDLE   JCPU   PCPU  WHAT
bluemang tty1      09:51    7:06m  0.05   0.05  /usr/bin/startplasma-wayland
bluemang pts/0     09:51    7:06m  8241.887.48  /usr/bin/kded5
bluemang pts/2     16:28    28:05  0.48   0.4   /usr/bin/zsh
bluemang pts/3     16:28    28:38  0.25   0.17  /usr/bin/zsh
```
fix #438

w: truncate long username

---

Cargo.lock
src/uu/slabtop/src/parse.rs
src/uu/slabtop/src/slabtop.rs
src/uu/vmstat/Cargo.toml
src/uu/vmstat/src/vmstat.rs

remains a sort issue. I have no idea about how GNU implementation sort it by name, especially the priority of `-`
parts of GNU outputs:
```
bio-128                     672    672    192     42
bio-192                    1024   1024    256     32
bio-224                      32     32    256     32
bio-256                      50     50    320     25
bio-352                    2058   2184    384     42
biovec-128                   16     16   2048     16
biovec-64                   512    512   1024     32
biovec-max                  416    448   4096      8
```
```
dmaengine-unmap-128        3450   4830   1088     30
dmaengine-unmap-256          15     15   2112     15
dma-kmalloc-128               0      0    128     32
dma-kmalloc-16                0      0     16    256
dma-kmalloc-192 …
```

vmstat: implement `--slabs`

---

Cargo.lock

This PR bumps `chrono-tz` from `0.10.3` to `0.10.4` in order to get rid of a handful of dependencies.

Bump `chrono-tz` from `0.10.3` to `0.10.4`

---

src/uu/vmstat/src/parser.rs
src/uu/vmstat/src/picker.rs
src/uu/vmstat/src/vmstat.rs
tests/by-util/test_vmstat.rs

This PR implemented `--disk`(`-d`), `--disk-sum`(`-D`), `--partition <device>`(`-p`).
So far, **all** the features of vmstat **on Linux** have been implemented.
```
$ cargo run -q vmstat -d && echo '\n' && vmstat -d
disk- ------------reads------------ ------------writes----------- -----IO------
total merged sectors      ms  total merged sectors      ms    cur    sec
nvme0n1  87787    629 15882401   47181 756219  25189 60103306 1911481      0    246
loop0      0      0       0       0      0      0       0       0      0      0
loop1      0      0       0       0      0      0       0       0      0      0
loop2      0      0       0       0      0      0       0       0      0      0
loop3      0      0       0       0      0      0       0       0      0      0
loop4      0      0 …
```

vmstat: implement `--disk` `--disk-sum` `--partition`

---

src/uu/pkill/src/pkill.rs
tests/by-util/test_pkill.rs

wrote a tool to test:
```
$ ./sigr                    
I'm 99648
recv a sig = 2 data = 10 data = 10
```
```
$ cargo run -q pkill -SIGINT -q 10 sigr -e
./sigr killed (pid 99648)
```

pkill: implement `--queue`

---

src/uu/pmap/src/maps_format_parser.rs

This PR fixes warnings from the [identity_op](https://rust-lang.github.io/rust-clippy/master/index.html#identity_op) lint.

pmap: fix warnings from `identity_op` lint in tests

---

src/uu/top/src/picker.rs

The old PR impl is exactly NI impl

top: implement `PR` `NI`

---

Cargo.lock
Cargo.toml

This PR manually bumps `ctor` from `0.4.1` to `0.5.0` because renovate fails with a "Artifact update problem" in https://github.com/uutils/procps/pull/485

Bump `ctor` from `0.4.1` to `0.5.0`

---

Cargo.lock
Cargo.toml

This PR manually bumps `windows` from `0.61.1` to `0.62.0` and `windows-sys` from `0.60.2` to `0.61.0` as `renovate` fails with an "Artifact update problem" in https://github.com/uutils/procps/pull/510 and https://github.com/uutils/procps/pull/511. The PR also bumps `dns-lookup` from `2.0.4` to `2.1.1` to get rid of an old `windows-sys` version.

Bump windows crates

---

Cargo.lock
Cargo.toml
tests/by-util/test_free.rs
tests/by-util/test_pgrep.rs
tests/by-util/test_pidof.rs
tests/by-util/test_pidwait.rs
tests/by-util/test_pkill.rs
tests/by-util/test_pmap.rs
tests/by-util/test_ps.rs
tests/by-util/test_pwdx.rs
tests/by-util/test_skill.rs
tests/by-util/test_slabtop.rs
tests/by-util/test_snice.rs
tests/by-util/test_sysctl.rs
tests/by-util/test_tload.rs
tests/by-util/test_top.rs
tests/by-util/test_vmstat.rs
tests/by-util/test_w.rs
tests/by-util/test_watch.rs

This PR bumps `uutest` from `0.1.0` to `0.2.0` and removes imports in tests that are no longer needed. It also makes some imports linux-only.

Bump `uutest` & remove unused imports in tests

---

Cargo.lock
Cargo.toml
src/uu/vmstat/Cargo.toml
src/uu/vmstat/src/picker.rs

This PR bumps `uucore` from `0.1.0` to <del>`0.2.0`</del>`0.2.2`. It also makes `vmstat` use `jiff` because the `custom-tz-fmt` feature has been removed from `uucore`. And to avoid using two datetime libraries in `vmstat`, `chrono` has been removed.

Bump `uucore` & adapt `vmstat` to removed `uucore` feature
